# All passwords are "redhatosp" for consistency with the GLS classroom default OpenShift admin password
apiVersion: v1
data:
  AdminPassword: cmVkaGF0b3Nw
  CeilometerPassword: cmVkaGF0b3Nw
  CinderDatabasePassword: cmVkaGF0b3Nw
  CinderPassword: cmVkaGF0b3Nw
  DatabasePassword: cmVkaGF0b3Nw
  DbRootPassword: cmVkaGF0b3Nw
  DesignateDatabasePassword: cmVkaGF0b3Nw
  DesignatePassword: cmVkaGF0b3Nw
  GlanceDatabasePassword: cmVkaGF0b3Nw
  GlancePassword: cmVkaGF0b3Nw
  HeatAuthEncryptionKey: cmVkaGF0b3Nw
  HeatDatabasePassword: cmVkaGF0b3Nw
  HeatPassword: cmVkaGF0b3Nw
  IronicDatabasePassword: cmVkaGF0b3Nw
  IronicInspectorDatabasePassword: cmVkaGF0b3Nw
  IronicInspectorPassword: cmVkaGF0b3Nw
  IronicPassword: cmVkaGF0b3Nw
  KeystoneDatabasePassword: cmVkaGF0b3Nw
  ManilaDatabasePassword: cmVkaGF0b3Nw
  ManilaPassword: cmVkaGF0b3Nw
  MetadataSecret: cmVkaGF0b3Nw
  NeutronDatabasePassword: cmVkaGF0b3Nw
  NeutronPassword: cmVkaGF0b3Nw
  NovaAPIDatabasePassword: cmVkaGF0b3Nw
  NovaAPIMessageBusPassword: cmVkaGF0b3Nw
  NovaCell0DatabasePassword: cmVkaGF0b3Nw
  NovaCell0MessageBusPassword: cmVkaGF0b3Nw
  NovaCell1DatabasePassword: cmVkaGF0b3Nw
  NovaCell1MessageBusPassword: cmVkaGF0b3Nw
  NovaPassword: cmVkaGF0b3Nw
  OctaviaDatabasePassword: cmVkaGF0b3Nw
  OctaviaPassword: cmVkaGF0b3Nw
  PlacementDatabasePassword: cmVkaGF0b3Nw
  PlacementPassword: cmVkaGF0b3Nw
  SwiftPassword: cmVkaGF0b3Nw
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
