apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: '' 
  desiredState:
    interfaces:
    - name: ovs-br1 
      type: ovs-bridge
      state: up
      bridge:
        options:
          stp: true
        port:
        - name: ens4
    ovn:
      bridge-mappings:
      - localnet: isolated-network
        bridge: ovs-br1 
        state: present
